# -*- coding: utf-8 -*-
"""Copy of Welcome to Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLZMTYP2UqtcGgxMl0iBpAJYOlUsdQHG

#Importing Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""# Loading the dataset"""

customers = pd.read_csv('Customers.csv')
products = pd.read_csv('Products.csv')
transactions = pd.read_csv('Transactions.csv')

"""#Merging Datasets"""

merged_df = transactions.merge(customers, on='CustomerID', how='left')  # Merge with Customers
merged_df = merged_df.merge(products, on='ProductID', how='left')
merged_df = merged_df.drop_duplicates()

print(merged_df.head())

"""#Distribution of Transactional value"""

plt.figure(figsize=(10, 6))
sns.histplot(merged_df['TotalValue'], kde=True)
plt.title('Distribution of Transaction Total Value')
plt.show()

"""# Boxplot of Transactional Total Value"""

plt.figure(figsize=(10, 6))
sns.boxplot(x=merged_df['TotalValue'])
plt.title('Boxplot of Transaction Total Value')
plt.show()

"""# Top Customers"""

top_customers = merged_df.groupby('CustomerID')['TotalValue'].sum().sort_values(ascending=False)
print(top_customers.head(5))

"""# Regional sales"""

regional_sales = merged_df.groupby('Region')['TotalValue'].sum().sort_values(ascending=False)
sns.barplot(x=regional_sales.index, y=regional_sales.values)
plt.title('Total Sales by Region')
plt.show()

"""# Top Products"""

top_products = merged_df.groupby('ProductName')['TotalValue'].sum().sort_values(ascending=False)
print(top_products.head(5))

"""# Total transactions happened in month"""

monthly_transactions_value = merged_df.groupby('YMonth')['TotalValue'].sum()

plt.figure(figsize=(10, 6))
t.plot(kind='line')
plt.title('Customer Total Spent Over Time')
plt.ylabel('Number of Signups')
plt.show()

"""# New Signups happened in months"""

merged_df['SignupDate'] = pd.to_datetime(merged_df['SignupDate'])
merged_df['SignupMonth'] = merged_df['SignupDate'].dt.to_period('M')
signup_trend = merged_df.groupby('SignupMonth').size()

plt.figure(figsize=(10, 6))
signup_trend.plot(kind='line')
plt.title('Customer Signups Over Time')
plt.ylabel('Number of Signups')
plt.show()

print(merged_df)

"""# Products in demand during different Months"""

prod = merged_df.groupby(['ProductName','YMonth'])['Quantity'].sum()
prod = pd.DataFrame(prod)
print(prod)